### PR TITLE
[routes router] add a pre handle hook to access route

### PR DESCRIPTION
**Pull request by syyang**
I initially tried adding a separate method to router for mapping url to route, but this doesn't work when the router is wrapped in function. I think using hook is the cleanest way.

### CODE REVIEW

**Comment by Raynos** [comment]
cc @Matt-Esch

**Comment by Raynos** [comment]
This will work. It seems strange that there is a callback..

**Comment by syyang** [comment]
ok. should i call `route.fn(req, res, params, callback);` directly. and not wrap it in cb then?

**Comment by syyang** [comment]
Updated.

**Pull request merged**
